// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __ctmcd_h__
#define __ctmcd_h__

#include "ctmcd_RcppExports.h"

#endif // __ctmcd_h__
