# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rNijTRiT_ModRej <- function(tmabs, te, gm) {
    .Call('ctmcd_rNijTRiT_ModRej', PACKAGE = 'ctmcd', tmabs, te, gm)
}

rNijTRiT_Unif <- function(tmabs, te, gm, tpm) {
    .Call('ctmcd_rNijTRiT_Unif', PACKAGE = 'ctmcd', tmabs, te, gm, tpm)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('ctmcd_RcppExport_registerCCallable', PACKAGE = 'ctmcd')
})
